feat. 경기장 생성 기능 구현
Clo-fi/Codeython-server pull request #52
Opened 2024-04-21 16:06 UTC by yongbyn

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 이슈 번호
- issue: #42 
- close #42 

### 반영 브랜치
ex) feat/login -> main

### 변경 사항
경기장 생성 기능 구현

### 테스트 결과
![image](https://github.com/Clo-fi/Codeython-server/assets/44955172/8291930e-8516-48cf-a729-d871f66b23eb)

2024-04-21 16:30 UTC, galaxian requested changes
채점 과정에 생성되고 지워지는 파일들이 올라온 것 같습니다.

2024-04-21 16:30 UTC, galaxian commented on src/main/java/clofi/codeython/room/service/RoomService.java
> +        }
예외 상황을 먼저 검증하면 불필요한 else 문이 사라져 코드가 깔끔해지는 효과가 있을 것 같습니다.
```
if (!(createRoomRequest.getLimitMemberCnt() == 2 || createRoomRequest.getLimitMemberCnt() == 4 || createRoomRequest.getLimitMemberCnt() == 6)) {
   throw new IllegalArgumentException("인원 제한 수는 2, 4, 6 중 하나여야 합니다.");
}

// 정상 룸 생성 로직

```

2024-04-21 16:30 UTC, galaxian commented on 3300bf69-6993-439e-b5ec-420b722a3cd5/Main.java
> +System.out.print(mapper.writeValueAsString(s.solution(mapper.readValue(args[0], int.class),mapper.readValue(args[1], int[].class))));}}
올라오면 안되는 파일인 것 같습니다. 확인해 보세요.

2024-04-21 16:30 UTC, galaxian commented on 3300bf69-6993-439e-b5ec-420b722a3cd5/Solution.java
> +}
올라오면 안되는 파일인 것 같습니다. 확인해 보세요.

2024-04-21 16:49 UTC, yongbyn commented on src/main/java/clofi/codeython/room/service/RoomService.java
> +        }
if (!true)가 있었네요..!
감사합니다  ^^

2024-04-21 16:50 UTC, yongbyn commented on 3300bf69-6993-439e-b5ec-420b722a3cd5/Main.java
> +System.out.print(mapper.writeValueAsString(s.solution(mapper.readValue(args[0], int.class),mapper.readValue(args[1], int[].class))));}}
네, 원인은 모르겠으나 깃 커밋을 revert하는 과정에서 파일이 자동으로 생성되어서 삭제하였습니다.

2024-04-22 00:58 UTC, zeno1030 approved these changes

2024-04-22 01:07 UTC, galaxian approved these changes

2024-04-22 01:22 UTC, merged